Initial commit with full Electron wallet code

diff --git a/contrib/make_tor b/contrib/make_tor
--- a/contrib/make_tor
+++ b/contrib/make_tor
@@ -49,8 +49,8 @@ if [ "$BUILD_TYPE" = "wine" ] ; then
     binary="tor.exe"
 fi
 host_strip "$here/$pkgname/dist/bin/$binary"
-mkdir -p "$here/../electronlambda/tor/bin"
-cp -fpv "$here/$pkgname/dist/bin/$binary" "$here/../electronlambda/tor/bin/." || fail "Could not copy the $pkgname binary to its destination"
+mkdir -p "$here/../electronfittexxcoin/tor/bin"
+cp -fpv "$here/$pkgname/dist/bin/$binary" "$here/../electronfittexxcoin/tor/bin/." || fail "Could not copy the $pkgname binary to its destination"
 $SHA256_PROG "$here/$pkgname/dist/bin/$binary"
-info "$binary has been placed in the 'electronlambda' folder."
+info "$binary has been placed in the 'electronfittexxcoin' folder."
 popd
